### ISSUE TITLE
When there is no `prebuilt` composer template some vital options are missing

### ISSUE THREAD

**Issue by gregharvey** [codeenigma/ce-dev#178]
If there's a `ce-dev.compose.prebuilt.yml` then it is simple copied to `docker-compose.yml` and all is fine, as long as your `prebuilt` file is correct. However, when there is only a `ce-dev.compose.yml` file and you run `ce-dev init`, it's the [`init.ts` file](https://github.com/codeenigma/ce-dev/blob/1.x/src/commands/init.ts) that builds `docker-compose.yml` step by step. We have some options these days that are very important, specifically:

```yaml
  # giving access to the host for local apps in macOS
  ports:
    - '3306:3306'
  # if this is missing containers cannot start
  cgroup: host
  # probably not vital, but we should set it
  platform: linux/amd64
```

We should make sure `init.ts` handles these parameters and can take them from `ce-dev.compose.yml` correctly, at the moment it builds `docker-compose.yml` files that make it impossible to start the containers if there is no `prebuilt` file.
