### ISSUE TITLE
Add install_command: "-y si" to deploy.yml

### ISSUE THREAD

**Issue by DionisioFG** [codeenigma/ce-dev#43]
ce-deploy now requires the var "install_command"

But the templates generated by ce-dev create doesn't include it by default.
We have to add:

```
- drupal:
        sites:
          - folder: "default"
            public_files: "sites/default/files"
            install_command: "-y si"
            ......
```

by default to ce-dev
